services:
  backend:
    container_name: backend
    build:
      context: ./backend/demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - WIKI_BACKEND_BASE_URL=http://backend:8080
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=wikidb
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      mysql:
        condition: service_healthy
    networks: [appnet]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/wiki"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_WIKI_API_BASE_URL=/api/wiki
        - VUE_CHAT_API_BASE_URL=/api/chat/message
    ports:
      - "8888:8888"
    networks:
      - appnet
    environment:
      - VUE_APP_API_URL=http://backend:8080
    depends_on:
      backend:
        condition: service_healthy

  mcp-client:
    build:
      context: .
      dockerfile: mcp-client/Dockerfile
    ports:
      - "8086:8086"
    networks: [appnet]

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: wikidb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -u$$MYSQL_USER -p$$MYSQL_PASSWORD -h 127.0.0.1 --silent",
        ]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [appnet]

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks: [appnet]

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks: [appnet]
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  appnet:

volumes:
  mysql_data:
  ollama-data:
